import React, { useState, useCallback, useMemo } from 'react'
import { Download, RefreshCw } from 'lucide-react'
import CasesTable from '@shared/components/cases/CasesTable'
import CaseDetailPanel from '@shared/components/cases/CaseDetailPanel'
import type { MedicalRecord } from '@lib/supabase-service'
import { useQuery } from '@tanstack/react-query'
import { supabase } from '@lib/supabase/config'
import { Card } from '@shared/components/ui/card'
import { useAuth } from '@app/providers/AuthContext'
import { useUserProfile } from '@shared/hooks/useUserProfile'
import DoctorFilterPanel from '@shared/components/cases/DoctorFilterPanel'

const MyCases: React.FC = React.memo(() => {
	const [selectedCase, setSelectedCase] = useState<MedicalRecord | null>(null)
	const [isPanelOpen, setIsPanelOpen] = useState(false)
	const [isFullscreen, setIsFullscreen] = useState(false)
	const [selectedDoctors, setSelectedDoctors] = useState<string[]>([])
	const [showDoctorFilter] = useState(false)
	const { user } = useAuth()
	useUserProfile()

	// Query for fetching only cases generated by the current user (admin/doctor) - optimized
	const casesQueryResult = useQuery({
		queryKey: ['my-medical-cases'],
		queryFn: async () => {
			if (!user) return { data: [] }
			
			const { data, error } = await supabase
				.from('medical_records_clean')
				.select('*')
				.eq('generated_by', user.id)
				.order('created_at', { ascending: false })
			
			if (error) {
				throw error
			}
			
			return { data: data || [] }
		},
		staleTime: 1000 * 60 * 5, // 5 minutes
		enabled: !!user, // Only run query if user is logged in
		refetchOnWindowFocus: false, // Prevent refetching on window focus
		refetchOnReconnect: false, // Prevent refetching on reconnect
	})

	const { refetch, isLoading } = casesQueryResult
	const cases: MedicalRecord[] = useMemo(() => casesQueryResult.data?.data || [], [casesQueryResult.data])
	const error = casesQueryResult.error

	const handleCaseSelect = useCallback((case_: MedicalRecord) => {
		setSelectedCase(case_)
		setIsPanelOpen(true)
	}, [])

	const handlePanelClose = useCallback(() => {
		setIsPanelOpen(false)
		// Delay clearing selected case to allow animation to complete
		setTimeout(() => setSelectedCase(null), 300)
	}, [])

	// Handle doctor filter change
	const handleDoctorFilterChange = useCallback((doctors: string[]) => {
		setSelectedDoctors(doctors)
	}, [])

	// Toggle doctor filter panel

	const handleRefresh = useCallback(() => {
		refetch()
	}, [refetch])

	// Filter cases by selected doctors
	const filteredCases = React.useMemo(() => {
		if (selectedDoctors.length === 0) return cases
		
		return cases.filter(caseItem => 
			caseItem.treating_doctor && selectedDoctors.includes(caseItem.treating_doctor.trim())
		)
	}, [cases, selectedDoctors])

	return (
		<div className="p-3 sm:p-6">
			{/* Page Title */}
			<div className="mb-4 sm:mb-6">
				<h1 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-gray-100">Mis Casos Generados</h1>
				{cases.length === 0 && !isLoading ? (
					<p className="text-sm text-gray-600 dark:text-gray-400 mt-1 sm:mt-2">
						No has generado ningún caso aún. Los casos aparecerán aquí cuando utilices el botón "Generar" en la sección
						de Casos.
					</p>
				) : (
					<p className="text-sm text-gray-600 dark:text-gray-400 mt-1 sm:mt-2">
						Aquí puedes ver todos los casos que has generado como médico
					</p>
				)}
			</div>

			{/* Action Buttons */}
			<div className="grid grid-cols-2 gap-2 sm:gap-4 mb-4 sm:mb-6">
				<Card className="col-span-1 grid hover:border-primary hover:-translate-y-1 hover:shadow-lg hover:shadow-primary/20 transition-all duration-300 shadow-lg">
					<button className="bg-white dark:bg-background rounded-xl p-2 sm:p-4 flex items-center gap-2 sm:gap-3">
						<div className="p-1 sm:p-2 bg-green-100 dark:bg-green-900/30 rounded-lg">
							<Download className="w-3 h-3 sm:w-4 sm:h-4 md:w-5 md:h-5 text-green-600 dark:text-green-400" />
						</div>
						<div className="text-left">
							<p className="text-xs sm:text-sm font-medium text-gray-700 dark:text-gray-300">Exportar</p>
							<p className="text-[10px] text-gray-500 dark:text-gray-400 hidden sm:block">Descargar datos</p>
						</div>
					</button>
				</Card>

				<Card className="col-span-1 grid hover:border-primary hover:-translate-y-1 hover:shadow-lg hover:shadow-primary/20 transition-all duration-300 shadow-lg">
					<button
						onClick={handleRefresh}
						disabled={isLoading}
						className="bg-white dark:bg-background rounded-xl p-2 sm:p-4 flex items-center gap-2 sm:gap-3"
					>
						<div className="p-1 sm:p-2 bg-orange-100 dark:bg-orange-900/30 rounded-lg">
							<RefreshCw
								className={`w-3 h-3 sm:w-4 sm:h-4 md:w-5 md:h-5 text-orange-600 dark:text-orange-400 ${
									isLoading ? 'animate-spin' : ''
								}`}
							/>
						</div>
						<div className="text-left">
							<p className="text-xs sm:text-sm font-medium text-gray-700 dark:text-gray-300">
								{isLoading ? 'Actualizando...' : 'Actualizar'}
							</p>
							<p className="text-[10px] text-gray-500 dark:text-gray-400 hidden sm:block">Recargar datos</p>
						</div>
					</button>
				</Card>
			</div>

			{/* Doctor Filter Panel - Conditionally rendered */}
			{showDoctorFilter && (
				<div className="mb-4 sm:mb-6">
					<DoctorFilterPanel cases={cases} onFilterChange={handleDoctorFilterChange} />
				</div>
			)}

			{/* Cases Table */}
			<CasesTable
				onCaseSelect={handleCaseSelect}
				cases={filteredCases}
				isLoading={isLoading}
				error={error}
				refetch={refetch}
				isFullscreen={isFullscreen}
				setIsFullscreen={setIsFullscreen}
			/>

			{/* Case Detail Panel */}
			<CaseDetailPanel
				case_={selectedCase}
				isOpen={isPanelOpen}
				onClose={handlePanelClose}
				onCaseSelect={handleCaseSelect}
			/>
		</div>
	)
})

MyCases.displayName = 'MyCases'

export default MyCases