import React, { useState, useCallback, useMemo, useEffect } from 'react'
import CasesTable from '@shared/components/cases/CasesTable'
import CaseDetailPanel from '@shared/components/cases/CaseDetailPanel'
import type { MedicalCaseWithPatient } from '@lib/medical-cases-service'
import { mapToLegacyRecords } from '@lib/mappers'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { getCasesWithPatientInfo } from '@lib/medical-cases-service'
import { supabase } from '@lib/supabase/config'
import { useAuth } from '@app/providers/AuthContext'
import DoctorFilterPanel from '@shared/components/cases/DoctorFilterPanel'

const MyCases: React.FC = React.memo(() => {
	const queryClient = useQueryClient()

	useEffect(() => {
		const channel = supabase
			.channel('realtime-my-cases')
			.on(
				'postgres_changes',
				{
					event: '*', // INSERT | UPDATE | DELETE
					schema: 'public',
					table: 'medical_records_clean',
				},
				() => {
					queryClient.invalidateQueries({ queryKey: ['my-medical-cases'] }) // tanstack refetch
				},
			)
			.subscribe()

		return () => {
			supabase.removeChannel(channel)
		}
	}, [queryClient])

	const [selectedCase, setSelectedCase] = useState<MedicalCaseWithPatient | null>(null)
	const [isPanelOpen, setIsPanelOpen] = useState(false)
	const [isFullscreen, setIsFullscreen] = useState(false)
	const [selectedDoctors, setSelectedDoctors] = useState<string[]>([])
	const [showDoctorFilter] = useState(false)
	const { user } = useAuth()

	// Query for fetching only cases generated by the current user (admin/doctor) - optimized
	const casesQueryResult = useQuery({
		queryKey: ['my-medical-cases'],
		queryFn: async () => {
			if (!user) return { data: [] }

			try {
				const result = await getCasesWithPatientInfo(1, 1000, {})
				// Filtrar por generated_by después de obtener los datos
				const filteredData = result.data.filter((case_) => case_.generated_by === user.id)
				return { data: filteredData }
			} catch (error) {
				throw error
			}
		},
		staleTime: 1000 * 60 * 5, // 5 minutes
		enabled: !!user, // Only run query if user is logged in
		refetchOnWindowFocus: false, // Prevent refetching on window focus
		refetchOnReconnect: false, // Prevent refetching on reconnect
	})

	const { refetch, isLoading } = casesQueryResult
	const cases: MedicalCaseWithPatient[] = useMemo(() => casesQueryResult.data?.data || [], [casesQueryResult.data])
	const error = casesQueryResult.error

	const handleCaseSelect = useCallback((case_: MedicalCaseWithPatient) => {
		setSelectedCase(case_)
		setIsPanelOpen(true)
	}, [])

	const handleLegacyCaseSelect = useCallback(
		(legacyCase: MedicalCaseWithPatient) => {
			// Find the original case from our data
			const originalCase = cases?.find((c) => c.id === legacyCase.id)
			if (originalCase) {
				handleCaseSelect(originalCase)
			}
		},
		[cases, handleCaseSelect],
	)

	const handlePanelClose = useCallback(() => {
		setIsPanelOpen(false)
		// Delay clearing selected case to allow animation to complete
		setTimeout(() => setSelectedCase(null), 300)
	}, [])

	// Handle doctor filter change
	const handleDoctorFilterChange = useCallback((doctors: string[]) => {
		setSelectedDoctors(doctors)
	}, [])

	// Filter cases by selected doctors
	const filteredCases = React.useMemo(() => {
		if (selectedDoctors.length === 0) return cases

		return cases.filter(
			(caseItem) => caseItem.treating_doctor && selectedDoctors.includes(caseItem.treating_doctor.trim()),
		)
	}, [cases, selectedDoctors])

	return (
		<div>
			{/* Page Title */}
			<div className="mb-4 sm:mb-6">
				<div>
					<h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-gray-100">Mis Casos Generados</h1>
					<div className="w-16 sm:w-24 h-1 bg-primary mt-2 rounded-full" />
				</div>
				{cases.length === 0 && !isLoading ? (
					<p className="text-sm text-gray-600 dark:text-gray-400 mt-1 sm:mt-2">
						No has generado ningún caso aún. Los casos aparecerán aquí cuando utilices el botón "Generar" en la sección
						de Casos.
					</p>
				) : (
					<p className="text-sm text-gray-600 dark:text-gray-400 mt-1 sm:mt-2">
						Aquí puedes ver todos los casos que has generado como médico
					</p>
				)}
			</div>

			{/* Doctor Filter Panel - Conditionally rendered */}
			{showDoctorFilter && (
				<div className="mb-4 sm:mb-6">
					<DoctorFilterPanel cases={cases ? mapToLegacyRecords(cases) : []} onFilterChange={handleDoctorFilterChange} />
				</div>
			)}

			{/* Cases Table */}
			<CasesTable
				onCaseSelect={handleLegacyCaseSelect}
				cases={filteredCases ? mapToLegacyRecords(filteredCases) : []}
				isLoading={isLoading}
				error={error}
				refetch={refetch}
				isFullscreen={isFullscreen}
				setIsFullscreen={setIsFullscreen}
			/>

			{/* Case Detail Panel */}
			<CaseDetailPanel
				case_={selectedCase}
				isOpen={isPanelOpen}
				onClose={handlePanelClose}
				onCaseSelect={handleCaseSelect}
			/>
		</div>
	)
})

MyCases.displayName = 'MyCases'

export default MyCases
