// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbqepjsxnqtldyvlntqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicWVwanN4bnF0bGR5dmxudHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjU3OTUsImV4cCI6MjA2NTcwMTc5NX0.Pq0Fu-Lv-MrrkrrAQM60TYGgyTIuOwu33tzU31rbDvY";

// Verificar que las variables estén definidas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Variables de Supabase no configuradas correctamente');
  console.error('SUPABASE_URL:', SUPABASE_URL);
  console.error('SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'Definida' : 'No definida');
}

console.log('🔗 Conectando a Supabase con tabla medical_records_clean:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    }
  }
});

// Test connection with the new 'medical_records_clean' table
supabase.from('medical_records_clean').select('count', { count: 'exact', head: true })
  .then(({ error }) => {
    if (error) {
      console.error('❌ Error de conexión con tabla medical_records_clean:', error);
      console.log('💡 Ejecuta las migraciones para crear la tabla medical_records_clean');
    } else {
      console.log('✅ Conexión con tabla medical_records_clean establecida correctamente');
    }
  })
  .catch((err) => {
    console.error('❌ Error inesperado conectando con tabla medical_records_clean:', err);
  });