/*
  # Add PDF ready status field to medical_records_clean table

  1. New Fields
    - `pdf_en_ready` (boolean, default false) - Indicates if PDF is ready for download
    
  2. Purpose
    - This field tracks whether a case has been processed and is ready for PDF generation
    - Used by the UI to determine which cases have downloadable PDFs
    - Automatically set to true when a case is generated by a doctor
*/

-- Add pdf_en_ready column if it doesn't exist
ALTER TABLE medical_records_clean 
ADD COLUMN IF NOT EXISTS pdf_en_ready boolean DEFAULT false;