/*
  # Add code column to medical_records_clean table

  1. Changes
    - Add `code` column to `medical_records_clean` table
    - Make it unique to ensure no duplicate codes
    - Add index for better performance

  2. Notes
    - The code will be generated by the application
    - Format: [caseType][yearSince2000][monthlyCounter][monthLetter]
    - Example: "125001A" (Citología, year 2025, first case, January)
*/

-- Add code column to medical_records_clean table
ALTER TABLE medical_records_clean 
ADD COLUMN code text UNIQUE;

-- Add index for better performance on code lookups
CREATE INDEX IF NOT EXISTS idx_medical_records_clean_code ON medical_records_clean(code);

-- Add comment to document the code format
COMMENT ON COLUMN medical_records_clean.code IS 'Unique case code format: [caseType][yearSince2000][monthlyCounter][monthLetter]';